# WAP to make an game of
letsdoit="A. ASSIGNMENT 1:


1. WHO I AM?
A.There are 135 crore people in just India and more than that many parts of the world.
But not one person is exactly similar to one and other.
Each person has their own characteristics, persona and idiosyncrasies.
THE “ANSWER” TO “WHO AM I” IS OUR IDENTITY. OUR IDENTITY IS OUR ALL-ENCOMPASSING SYS
TEM OF
MEMORIES, EXPERIENCE, FEELINGS, THOUGHTS, RELATIONSHIPS, AND VALUES THAT DEFINE WH
O EACH OF US IS.
IT'S THE STUFF THAT MAKES UP A “SELF.” ... BECAUSE WE CAN BREAK UP IDENTITY INTO COMPO
NENTS (VALUES,
EXPERIENCES, RELATIONSHIP).

2.WHAT IS THE PURPOSE OF MY LIFE?
A. MAKING MY FAMILY HAPPY.
MAKING THE WORLD A BETTER PLACE.

3. WHEN DO I FEEL 'HAPPY' THE MOST?
A. HOLD ON TO MY VALUES. ...
ACCEPT THE GOOD. ...
IMAGINE THE BEST. ...
DO THINGS I LOVE. ...
FIND PURPOSE. ...

4. IS THE AIM OF MY LIFE MATCHING WITH MY DEFINATION OF HAPPINESS?
A. YES, THE AIM OF MY LIFE IS MATCHING WITH THE MY DEFINATION OF HAPPINESS AS I FOLLO
W MY VALUES
ON DAY TO DAY LIFE.5. WHAT IS LOVE TO ME? OR HOW DO I DEFINE LOVE?
A. “LOVE IS AN INTENSE FEELING OF DEEP AFFECTION.”
ACCORDING TO ME GIVING RESPECT TO SOMEONE OR UNDERSTANDING THEIR VIEWS SHOW YO
UR LOVE TOWARDS
THEM.




2. ASSIGNMENT 2:
1.I. SERACH IN GOOGLE FOR THE " 12 GRADUATE ATTRIBUTES AND LIST THEM ALONG WITH THEI
R
DEFINATION. "

A.THE 12 GRADUATE ATTRIBUTES*:
1. (KB) A KNOWLEDGE BASE FOR ENGINEERING: DEMONSTRATED COMPETENCE IN UNIVERSITY
LEVEL
MATHEMATICS, NATURAL SCIENCES, ENGINEERING FUNDAMENTALS, AND SPECIALIZED ENGINE
ERING
KNOWLEDGE APPROPRIATE TO THE PROGRAM.


2. (PA) PROBLEM ANALYSIS: AN ABILITY TO USE APPROPRIATE KNOWLEDGE AND SKILLS TO IDE
NTIFY, FORMULATE,
ANALYZE, AND SOLVE COMPLEX ENGINEERING PROBLEMS IN ORDER TO REACH SUBSTANTIATED CONCLUSIONS


3. (INV.) INVESTIGATION: AN ABILITY TO CONDUCT INVESTIGATIONS OF COMPLEX PROBLEMS B
Y METHODS THAT
INCLUDE APPROPRIATE EXPERIMENTS, ANALYSIS AND INTERPRETATION OF DATA AND SYNTHE
SIS OF INFORMATION
IN ORDER TO REACH VALID CONCLUSIONS.


4. (DES.) DESIGN: AN ABILITY TO DESIGN SOLUTIONS FOR COMPLEX, OPEN-ENDED ENGINEERING
PROBLEMS AND
TO DESIGN SYSTEMS, COMPONENTS OR PROCESSES THAT MEET SPECIFIED NEEDS WITH APPROP
RIATE
ATTENTION TO HEALTH AND SAFETY RISKS, APPLICABLE STANDARDS, AND ECONOMIC, ENVIRO
NMENTAL, CULTURAL
AND SOCIETAL CONSIDERATIONS.

5. (TOOLS) USE OF ENGINEERING TOOLS: AN ABILITY TO CREATE, SELECT, APPLY, ADAPT, AND E
XTEND
APPROPRIATE TECHNIQUES, RESOURCES, AND MODERN ENGINEERING TOOLS TO A RANGE OF EN
GINEERING
ACTIVITIES, FROM SIMPLE TO COMPLEX, WITH AN UNDERSTANDING OF THE ASSOCIATED LIMIT
ATIONS.

6. (TEAM) INDIVIDUAL AND TEAMWORK: AN ABILITY TO WORK EFFECTIVELY AS A MEMBER AN
D LEADER IN
TEAMS, PREFERABLY IN A MULTI-DISCIPLINARY SETTING.

7. (COMM.) COMMUNICATION SKILLS: AN ABILITY TO COMMUNICATE COMPLEX ENGINEERING C
ONCEPTS WITHIN
THE PROFESSION AND WITH SOCIETY AT LARGE. SUCH ABILITY INCLUDES READING, WRITING, S
PEAKING AND
LISTENING, AND THE ABILITY TO COMPREHEND AND WRITE EFFECTIVE REPORTS AND DESIGN D
OCUMENTATION,
AND TO GIVE AND EFFECTIVELY RESPOND TO CLEAR INSTRUCTIONS.

8. (PROF.) PROFESSIONALISM: AN UNDERSTANDING OF THE ROLES AND RESPONSIBILITIES OF TH
E PROFESSIONAL
ENGINEER IN SOCIETY, ESPECIALLY THE PRIMARY ROLE OF PROTECTION OF THE PUBLIC AND TH
E PUBLIC INTEREST.

9. (IMPACTS) IMPACT OF ENGINEERING ON SOCIETY AND THE ENVIRONMENT: AN ABILITY TO AN
ALYZE SOCIAL AND
ENVIRONMENTAL ASPECTS OF ENGINEERING ACTIVITIES. SUCH ABILITY INCLUDES AN UNDERST
ANDING OF THE
INTERACTIONS THAT ENGINEERING HAS WITH THE ECONOMIC, SOCIAL, HEALTH, SAFETY, LEGAL
, AND CULTURAL
ASPECTS OF SOCIETY, THE UNCERTAINTIES IN THE PREDICTION OF SUCH INTERACTIONS; AND T
HE CONCEPTS OF
SUSTAINABLE DESIGN AND DEVELOPMENT AND ENVIRONMENTAL STEWARDSHIP.

10. (ETHICS) ETHICS AND EQUITY: AN ABILITY TO APPLY PROFESSIONAL ETHICS, ACCOUNTABILI
TY, AND EQUITY.
11. (ECON.) ECONOMICS AND PROJECT MANAGEMENT: AN ABILITY TO APPROPRIATELY INCORPO
RATE ECONOMICS
AND BUSINESS PRACTICES INCLUDING PROJECT, RISK, AND CHANGE MANAGEMENT INTO THE PR
ACTICE OF
ENGINEERING AND TO UNDERSTAND THEIR LIMITATIONS.

12. (LL) LIFE-LONG LEARNING: AN ABILITY TO IDENTIFY AND TO ADDRESS THEIR OWN EDUCATI
ONAL NEEDS IN A
CHANGING WORLD IN WAYS SUFFICIENT TO MAINTAIN THEIR COMPETENCE AND TO ALLOW THE
M TO CONTRIBUTE
TO THE ADVANCEMENT OF KNOWLEDGE


II. FIND OUT WHICH OF THIS ATTRIBUTES DO I POSES AND LIST THEM?

A. 1. (KB) A KNOWLEDGE BASE FOR ENGINEERING: DEMONSTRATED COMPETENCE IN UNIVERSIT
Y LEVEL
MATHEMATICS, NATURAL SCIENCES, ENGINEERING FUNDAMENTALS, AND SPECIALIZED ENGINE
ERING
KNOWLEDGE APPROPRIATE TO THE PROGRAM.

2. (INV.) INVESTIGATION: AN ABILITY TO CONDUCT INVESTIGATIONS OF COMPLEX PROBLEMS B
Y METHODS THAT
INCLUDE APPROPRIATE EXPERIMENTS, ANALYSIS AND INTERPRETATION OF DATA AND SYNTHE
SIS OF INFORMATION
IN ORDER TO REACH VALID CONCLUSIONS.

3. (DES.) DESIGN: AN ABILITY TO DESIGN SOLUTIONS FOR COMPLEX, OPEN-ENDED ENGINEERING
PROBLEMS AND
TO DESIGN SYSTEMS, COMPONENTS OR PROCESSES THAT MEET SPECIFIED NEEDS WITH APPROP
RIATE
ATTENTION TO HEALTH AND SAFETY RISKS, APPLICABLE STANDARDS, AND ECONOMIC,

ENVIRONMENTAL, CULTURAL
AND SOCIETAL CONSIDERATIONS.

6. (TEAM) INDIVIDUAL AND TEAMWORK: AN ABILITY TO WORK EFFECTIVELY AS A MEMBER AND
LEADER IN
TEAMS, PREFERABLY IN A MULTI-DISCIPLINARY SETTING.

9. (IMPACTS) IMPACT OF ENGINEERING ON SOCIETY AND THE ENVIRONMENT: AN ABILITY TO AN
ALYZE SOCIAL AND
ENVIRONMENTAL ASPECTS OF ENGINEERING ACTIVITIES. SUCH ABILITY INCLUDES AN UNDERST
ANDING OF THE
INTERACTIONS THAT ENGINEERING HAS WITH THE ECONOMIC, SOCIAL, HEALTH, SAFETY, LEGAL
, AND CULTURAL
ASPECTS OF SOCIETY, THE UNCERTAINTIES IN THE PREDICTION OF SUCH INTERACTIONS; AND T
HE CONCEPTS OF
SUSTAINABLE DESIGN AND DEVELOPMENT AND ENVIRONMENTAL STEWARDSHIP.



 ASSIGNMENT -3

ASSIGNMENT QUESTION:
A. REVIEW THE CONTENT OF THE VIDEO LECTURE AND PUT FORTH YOUR VIEWS ON “BASIC HUM
AN
ASPIRATIONS”?
A. OKAY, SO IT WAS A VERY NICE VIDEO. I HAVE LEARNT MANY NEW THINGS FROM THIS VIDEO.
NOW A DAYS IT HAS BECOME NECESSARY TO LOOK UP INTO THIS THINHGS SPECIALLY FOR THE
UPCOMPING YOUTH.
NOT ONLY THAT, IT HAS BEEN A MOTIVATIONAL VIDEO TOO.
THANK YOU SIR FOR THIS AMAZING PROGRAM.
B. HOW WILL YOU PROGRAMME YOUR “PURPOSE” KEEPING AN EYE TO THE VIEW YOU EXPRESS?
A.PLANNING YOUR PRESENTATION
A LABYRINTHPREPARING A PRESENTATION CAN BE AN OVERWHELMING EXPERIENCE IF YOU AL
LOW IT TO BE ONE.
THE STRATEGIES AND STEPS BELOW ARE PROVIDED TO HELP YOU BREAK DOWN WHAT YOU MIG
HT VIEW AS A LARGE JOB
INTO SMALLER, MORE MANAGEABLE TASKS.STEP 1: ANALYZE YOUR AUDIENCE

1.THE FIRST STEP IN PREPARING A PRESENTATION IS TO LEARN MORE ABOUT THE AUDIENCE TO
WHOM YOU'LL BE
SPEAKING.

2.IT'S A GOOD IDEA TO OBTAIN SOME INFORMATION ON THE BACKGROUNDS, VALUES, AND INTE
RESTS
OF YOUR AUDIENCE SO THAT YOU UNDERSTAND WHAT THE AUDIENCE MEMBERS MIGHT EXPEC
T FROM YOUR
PRESENTATION.

STEP 2: SELECT A TOPIC

1.NEXT, IF POSSIBLE SELECT A TOPIC THAT IS OF INTEREST TO THE AUDIENCE AND TO YOU.
IT WILL BE MUCH EASIER TO DELIVER A PRESENTATION THAT THE AUDIENCE FINDS RELEVANT,
AND MORE ENJOYABLE TO
RESEARCH A TOPIC THAT IS OF INTEREST TO YOU.

STEP 3: DEFINE THE OBJECTIVE OF THE PRESENTATION

1.ONCE YOU HAVE SELECTED A TOPIC, WRITE THE OBJECTIVE OF THE PRESENTATION IN A SINGL
E CONCISE STATEMENT.

2.THE OBJECTIVE NEEDS TO SPECIFY EXACTLY WHAT YOU WANT YOUR AUDIENCE TO LEARN FR
OM YOUR PRESENTATION.

3.BASE THE OBJECTIVE AND THE LEVEL OF THE CONTENT ON THE AMOUNT OF TIME YOU HAVE F
OR THE PRESENTATION
AND THE BACKGROUND KNOWLEDGE OF THE AUDIENCE.

4.USE THIS STATEMENT TO HELP KEEP YOU FOCUSED AS YOU RESEARCH AND DEVELOP THE PRE
SENTATION.
PREPARING THE CONTENT OF YOUR PRESENTATION

STEP 4: PREPARE THE BODY OF THE PRESENTATION
 1.PRESENT DATA AND FACTS

2.READ QUOTES FROM EXPERTS

3.RELATE PERSONAL EXPERIENCES

4.PROVIDE VIVID DESCRIPTIONS

5.AND REMEMBER, AS YOU PLAN THE BODY OF YOUR PRESENTATION IT'S IMPORTANT TO PROVI
DE VARIETY.

6.LISTENERS MAY QUICKLY BECOME BORED BY LOTS OF FACTS OR THEY MAY TIRE OF HEARING
STORY AFTER STORY.

STEP 5: PREPARE THE INTRODUCTION AND CONCLUSION

1.MAKE THE INTRODUCTION RELEVANT TO THE LISTENERS' GOALS, VALUES, AND NEEDS

2.ASK QUESTIONS TO STIMULATE THINKING

3.SHARE A PERSONAL EXPERIENCE

4.BEGIN WITH A JOKE OR HUMOROUS STORY

5.PROJECT A CARTOON OR COLORFUL VISUAL

6.MAKE A STIMULATING OR INSPIRATIONAL STATEMENT

7.GIVE A UNIQUE DEMONSTRATION
PRACTICING AND DELIVERING

STEP 6: PRACTICE DELIVERING THE PRESENTATION

1.SPEAKING FROM MEMORY

2.SPEAKING FROM NOTES

3.A NOTE CARD.

4.SPEAKING FROM TEXT

5.USING A COMBINATION OF METHODS




ASSIGNMENT 4


PREPARE A SHORT SPEECH ON YOUR PERSONALITY TYPE STRENGTHS AND WEAKNESS (IF ANY)

A. MY PERSONALITY IS LIKE AN ADVOCATE.
“TREAT PEOPLE AS IF THEY WERE WHAT THEY OUGHT TO BE AND YOU HELP THEM TO BECOME
WHAT THEY ARE CAPABLE OF BEING.”
ADVOCATES ARE THE RAREST PERSONALITY TYPES OF ALL. STILL, ADVOCATES LEAVE THEIR M
ARK ON THE WORLD.
THEY HAVE A DEEP SENSE OF IDEALISM AND INTEGRITY, BUT THEY AREN’T IDLE DREAMERS –
THEY TAKE CONCRETE STEPS TO REALIZE THEIR GOALS AND MAKE A LASTING IMPACT.
ADVOCATES’ UNIQUE COMBINATION OF PERSONALITY TRAITS MAKES THEM COMPLEX AND QUI
TE VERSATILE.
FOR EXAMPLE, ADVOCATES CAN SPEAK WITH GREAT PASSION AND CONVICTION, ESPECIALLY
WHEN STANDING UP FOR
THEIR IDEALS.
AT OTHER TIMES, HOWEVER, THEY MAY CHOOSE TO BE SOFT-SPOKEN AND UNDERSTATED, PRE
FERRING TO KEEP THE
PEACE RATHER THAN CHALLENGE OTHERS.
STRENGTH
CREATIVE – ADVOCATE PERSONALITIES ENJOY FINDING THE PERFECT SOLUTION FOR THE PEOPL
E THEY CARE ABOUT.
TO DO THIS, THEY DRAW ON THEIR VIVID IMAGINATION AND THEIR STRONG SENSE OF COMPAS
SION.
THIS CAN MAKE THEM EXCELLENT COUNSELORS AND ADVISORS.
INSIGHTFUL – ADVOCATES TYPICALLY STRIVE TO MOVE PAST APPEARANCES AND GET TO THE H
EART OF THINGS.
THIS CAN GIVE THEM AN ALMOST UNCANNY ABILITY TO UNDERSTAND PEOPLE’S TRUE MOTIVA
TIONS, FEELINGS,
AND NEEDS.
PRINCIPLED – PEOPLE WITH THE ADVOCATE PERSONALITY TYPE TEND TO HAVE DEEPLY HELD B
ELIEFS,
AND THEIR CONVICTION OFTEN SHINES THROUGH WHEN THEY SPEAK OR WRITE ABOUT SUBJEC
TS THAT MATTER
TO THEM.
ADVOCATES CAN BE COMPELLING AND INSPIRING COMMUNICATORS, WITH THEIR IDEALISM PE
RSUADING EVEN
THE HARDEST OF SKEPTICS.
PASSIONATE – ADVOCATES CAN PURSUE THEIR IDEALS WITH A SINGLE-MINDEDNESS THAT MAY
CATCH OTHERS OFF
GUARD.
THESE PERSONALITIES RARELY SETTLE FOR “GOOD ENOUGH,” AND THEIR WILLINGNESS TO DIS
RUPT THE STATUS
QUO MAY NOT PLEASE EVERYONE. THAT SAID, ADVOCATES’ PASSION FOR THEIR CHOSEN CAUS
E IS A KEY ASPECT OF THEIR PERSONALITY.
ALTRUISTIC – ADVOCATES GENERALLY AIM TO USE THEIR STRENGTHS FOR THE GREATER GOOD
– THEY RARELY ENJOY
SUCCEEDING AT OTHER PEOPLE’S EXPENSE.
THEY TEND TO THINK ABOUT HOW THEIR ACTIONS AFFECT OTHERS, AND THEIR GOAL IS TO BE
HAVE IN A WAY
THAT WILL HELP THE PEOPLE AROUND THEM
AND MAKE THE WORLD A BETTER PLACE.
WEAKNESS
SENSITIVE TO CRITICISM – WHEN SOMEONE CHALLENGES THEIR PRINCIPLES OR VALUES, ADVO
CATES MAY REACT
STRONGLY.
PEOPLE WITH THIS PERSONALITY TYPE CAN BECOME DEFENSIVE IN THE FACE OF CRITICISM AN
D CONFLICT,
PARTICULARLY
WHEN IT COMES TO ISSUES THAT ARE NEAR TO THEIR HEARTS. RELUCTANT TO OPEN UP – ADVOCATES VALUE HONESTY, BUT THEY’RE ALSO PRIVATE.
THEY MAY FIND IT DIFFICULT TO OPEN UP AND BE VULNERABLE ABOUT THEIR STRUGGLES.
THIS MIGHT ALSO BE BECAUSE THEY THINK THEY NEED TO SOLVE THEIR PROBLEMS ON THEIR
OWN OR DON’T
WANT TO BURDEN OTHER PEOPLE WITH THEIR ISSUES.
WHEN ADVOCATES DON’T ASK FOR HELP, THEY MAY INADVERTENTLY HOLD THEMSELVES BAC
K OR CREATE
DISTANCE IN THEIR RELATIONSHIPS.
PERFECTIONISTIC – THE ADVOCATE PERSONALITY TYPE IS ALL BUT DEFINED BY IDEALISM.
WHILE THIS IS A WONDERFUL QUALITY IN MANY WAYS, AN IDEAL SITUATION IS NOT ALWAYS P
OSSIBLE.
ADVOCATES MIGHT FIND IT DIFFICULT TO APPRECIATE THEIR JOBS, LIVING SITUATIONS, OR REL
ATIONSHIPS
IF THEY’RE CONTINUALLY FIXATING ON IMPERFECTIONSAND WONDERING WHETHER THEY SHO
ULD BE LOOKING
FOR SOMETHING BETTER.
AVOIDING THE ORDINARY – ADVOCATE PERSONALITIES TEND TO BE MOTIVATED BY A SENSE OF
HAVING A GREATER
PURPOSE IN LIFE.
THEY MIGHT CONSIDER IT TEDIOUS OR UNNECESSARY TO BREAK THEIR BIG VISIONS INTO SMA
LL,
MANAGEABLE STEPS.
BUT THEY MAY BE SETTING THEMSELVES UP FOR FRUSTRATION IF THEY DON’T TURN THEIR DR
EAMS INTO
EVERYDAY ROUTINES AND TO-DO LISTS.
WITHOUT THESE SPECIFICS, THEIR GOALS MAY NEVER MATERIALIZE.
PRONE TO BURNOUT – ADVOCATES’ PERFECTIONISM AND RESERVE MAY LEAVE THEM WITH FE
W OPTIONS FOR LETTING
OFF STEAM. PEOPLE WITH THIS PERSONALITY TYPE CAN EXHAUST THEMSELVES IF THEY DON’T
FIND A WAY TO BALANCE
THEIR DRIVE
TO HELP OTHERS WITH NECESSARY SELF-CARE AND REST.



ASSIGNMENT 5

MATCH THE FOLLOWING NEGOTIATION STRATEGIES WITH THEIR CORRESPONDING BUSINESS SIT
UATIONS
MATCHING EXERCISE
YOUR SCORE IS 78%.
ADJOURNMENT OF A SESSION A SESSION THAT SEEMS TO LEAD NOWHERE
APOLOGY SOMETHING THAT HAS BEEN SAID OR A GESTURE BEEN MADE THAT DOES NOT ADHER
E TO BUSINESS
ETHICS
CONTROL A SITUATION THAT DEMANDS RESTRAINT FROM MEMBERS
COLLABORATION WHEN RESULTS LIKE LONG-TERM BUSINESS RELATIONSHIPS ARE DESIRED
HUMOUR TO TACKLE STRESSFUL AND BELLIGERENT SITUATIONS
RESPECT IN SITUATIONS OF CULTURAL DIVERSITY IN A GROUP OR IN CLIENTS
ARBRITRATION TO DEAL WITH AN IMPASSE IN A BUSINESS DISCUSSION


ASSIGNMENT 6
 1. PROGRESS OF ENGLISH LANGUAGE EDUCATION IN INDIA.

A.ENGLISH EVEN TODAY CONTINUES TO ACT AS AN INDISPENSABLE 'LINK' LANGUAGE.
ENGLISH SYMBOLIZES IN INDIAN MINDS BETTER EDUCATION, BETTER CULTURE AND BETTER IN
TELLECT.
IT IS STILL FREELY USED IN ADMINISTRATION, JUDICIARY, IN EDUCATION AND EVEN FOR LITER
ARY PURPOSES IN INDIA.
ENGLISH IS TAUGHT AS A SECOND LANGUAGE AT EVERY STAGE OF EDUCATION IN ALL STATES
OF INDIA
AND HAS BEEN ACCEPTED AS THE MAIN MEDIUM OF INSTRUCTION IN HIGHER EDUCATION
ENGLISH IS ALSO THE STATE LANGUAGE OF TWO STATES IN EASTERN INDIA, MEGHALAYA AND
NAGALAND.2. WHAT IS MY UNDERSTANDING ABOUT THE PROGRESS OF ENGLISH LANGUAGE TE
ACHING IN INDIA.

A. ENGLISH IS THE LANGUAGE OF EVERY LATEST BUSINESS IN THE WORLD. WITH THE RAPID AD
VANCEMENTS IN
TECHNOLOGY,
ENGLISH HAS NOT ONLY INCREASED EMPLOYMENT, BUT HAS ALSO HELPED A LOT IN COMMUNI
CATION.
THE BASIS OF EVERY RELATION IS COMMUNICATION AND ENGLISH HAS BECOME A WINDOW TO
GLOBAL
COMMUNICATION.
IMPORTANCE OF ENGLISH
IT S IMPOSSIBLE TO IMAGINE THE WORLD WITHOUT THE TWO E S : ELECTRONIC COMMUNICATI
ON AND ENGLISH.
ENGLISH IS ALL OVER THE INTERNET, BOOKS AND ALL MEDIA.
ENGLISH LANGUAGE IS FOLLOWED BY ALMOST ALL THE DEVELOPED AND DEVELOPING COUNT
RIES TODAY.
ENGLISH IN INDIA

3. WHAT ARE THE SPECIFIC FEATURES ON WHICH ENGLISH LANGUAGE TEACHING IN MODERN D
AY
ALSO DEPEND?

A.1.TASK-BASED APPROACH. TRADITIONAL CURRICULUM DESIGN AND CLASS PLANNING REVOL
VED AROUND THE TOPICS
CONSIDERED USEFUL FOR STUDENTS. ...

2.PROJECT-BASED APPROACH. ...

3.LEXICAL SYLLABUS. ...

4.USING SMARTPHONES IN THE CLASSROO"
x=""
new=""

l=len(letsdoit)
for i in range(0,l):
    if(letsdoit[i].isupper()):
        x=(letsdoit[i].lower())
        new=new.__add__(x)
    else:
        x=letsdoit[i]
        new=new.__add__(x)
    x=""
print(new)

